title:            jennifercooper.ca
description:      Jennifer Cooper's personal website.
url:              jennifercooper.ca
signoff:          # Your name.
disqus_shortname: # disqus comment thread for post header options. ( leave blank if unwanted. )
facebook_appid:   # appid for like button, remove from /_includes/share.html if unwanted.
google_analytics: # set tracking, remove from /javascripts/basic.js if unwanted.

links:
  - name:         About
    url:          /about
  - name:         Blog
    url:          http://jennifercooper.ca
    external:     true
  - name:         Hire Me
    url:          /hireme
  - name:         Email
    url:          mailto:cooper.jennl@gmail.com
    external:     true
  - name:         GitHub
    url:          http://github.com/jenncoop
    external:     true
pygments:         true
permalink:        pretty
markdown:         redcarpet
redcarpet:
  extensions:
    - smart
